# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
dist: xenial
cache: packages
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsecret-1-dev
      - libsodium-dev

jobs:
  include:
  - r: 3.4
  - r: release
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true