# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
dist: xenial
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsecret-1-dev
      - libsodium-dev

before_install:
  - Rscript -e 'remotes::install_github("meerpatelmd/cave")'

jobs:
  include:
  - r: 3.4
  - r: release
    before_deploy:
    - Rscript -e 'remotes::install_github("r-lib/pkgdown", ref = "48e12e0")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true